FROM rust:1.65-slim-bullseye as builder

WORKDIR /zero2prod

RUN cargo install --root ./ sqlx-cli --no-default-features --features rustls,postgres

COPY ./migrations ./migrations

FROM debian:bullseye-slim

WORKDIR /zero2prod
COPY --from=builder /zero2prod/migrations ./migrations
COPY --from=builder /zero2prod/bin/sqlx .

CMD ["./sqlx", "migrate", "run"]
