version: '3.8'

services:
  newsletter.db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - newsletterdbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123
      - POSTGRES_DB=newsletter

  newsletter.redis:
    image: redis:6
    ports:
      - "6379:6379"
  
  newsletter.db.migrations:
    depends_on:
      - newsletter.db
    image: newsletter.db.migrations
    build:
      context: ./
      dockerfile: Dockerfile.migrations
    environment:
      - DATABASE_URL=postgresql://postgres:Password123@newsletter.db:5432/newsletter?sslmode=disable

volumes:
  newsletterdbdata: