application:
  port: 8000
  host: 127.0.0.1
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "Password123"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "test-token"
  timeout_milliseconds: 10000